#!/usr/bin/with-contenv /bin/ash

INCLUDE_INI="/etc/uwsgi-dpaste.ini"

cat << EOF >> "${INCLUDE_INI}"
[uwsgi]

chdir           = ${APP_PATH}
module          = dpaste.wsgi
home            = ${VIRTUAL_ENV}

binary-path     = ${VIRTUAL_ENV}/bin/python3
check-static    = ${APP_PATH}/.static

virtualenv      = ${VIRTUAL_ENV}/lib/python${PYTHON_VERSION}/site-packages
EOF

sed -E -i -e '/^\s*client_body_buffer_size/d' -e '/.*location\s\/\s\{/a\\t\tclient_body_buffer_size 64k;' /etc/nginx/conf.d/default.conf

