#!/usr/bin/with-contenv /bin/sh

LOCAL_SETTINGS="${APP_PATH}/dpaste/settings/local.py"
SQLITE_NAME="${APP_PATH}/db/dpaste.sqlite"

# default to debugging disabled
DEBUG=False

if [ ! -z ${DEBUG+set} ]; then
	case $DEBUG in
		true|True|yes|on)
			DEBUG=True
			;;
	esac
fi
sed -E -i "s/(DEBUG\s*=\s*)(.*)$/\1${DEBUG}/" $LOCAL_SETTINGS

ad_name="none"
ad_email="none@nowhere.com"

if [ ! -z ${ADMIN_NAME} ]; then
	ad_name=$ADMIN_NAME
fi

if [ ! -z ${ADMIN_EMAIL} ]; then
	ad_email=$ADMIN_EMAIL
fi

sed -E -i "/ADMINS\s*=\s*\(/a \    ('${ad_name}', '${ad_email}')," $LOCAL_SETTINGS

if [ ! -z ${DB_TYPE+set} ]; then
	# remove existing settings
	sed -E -i "/^[[:blank:]]*'(NAME|HOST|USER|PASSWORD)':[[:blank:]]*'\S+',[[:blank:]]*$/d" $LOCAL_SETTINGS

	if [ $DB_TYPE == "mysql" ]; then
		db_type="mysql"
	elif [ $DB_TYPE == "postgres" ] || [ $DB_TYPE == "postgresql" ]; then
		db_type="postgresql"
	else
		db_type="sqlite3"
		DB_NAME=$SQLITE_NAME
	fi
	sed -E -i "s/('ENGINE':\s+'django\.db\.backends\.)(\w*)(',)/\1$db_type\3/" $LOCAL_SETTINGS
fi

[ ! -z ${DB_NAME+set} ] && sed -E -i "/('ENGINE':\s+'django\.db\.backends\.)(\w*)(',)/a \	'NAME': '$DB_NAME'," $LOCAL_SETTINGS
[ ! -z ${DB_HOST+set} ] && sed -E -i "/('ENGINE':\s+'django\.db\.backends\.)(\w*)(',)/a \	'HOST': '$DB_HOST'," $LOCAL_SETTINGS
[ ! -z ${DB_USER+set} ] && sed -E -i "/('ENGINE':\s+'django\.db\.backends\.)(\w*)(',)/a \	'USER': '$DB_USER'," $LOCAL_SETTINGS
[ ! -z ${DB_PASSWORD+set} ] && sed -E -i "/('ENGINE':\s+'django\.db\.backends\.)(\w*)(',)/a \	'PASSWORD': '$DB_PASSWORD'," $LOCAL_SETTINGS
[ ! -z ${EXPIRE_DEFAULT+set} ] && sed -E -i "s/(EXPIRE_DEFAULT\s*=\s*)(.*)$/\1$EXPIRE_DEFAULT/" $LOCAL_SETTINGS
[ ! -z ${SECRET_KEY+set} ] && sed -E -i "s/(SECRET_KEY\s*=\s*')(\S*)(')/\1$SECRET_KEY\3/" $LOCAL_SETTINGS

python3 ./manage.py makemigrations --noinput
python3 ./manage.py migrate --noinput
